// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2oTF6-TcOS745IjUOunY-6w1yxc4MlhQ',
    appId: '1:922907195481:web:1053e45a2fe7ff14e15948',
    messagingSenderId: '922907195481',
    projectId: 'scandit-f9d6a',
    authDomain: 'scandit-f9d6a.firebaseapp.com',
    storageBucket: 'scandit-f9d6a.appspot.com',
    measurementId: 'G-3ZBW388QL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWynS4mlgbfC4b0PkbKjcpC2mpimZ3b8',
    appId: '1:922907195481:android:f65f26f0ac558b95e15948',
    messagingSenderId: '922907195481',
    projectId: 'scandit-f9d6a',
    storageBucket: 'scandit-f9d6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoLmYkApILW7Ii5mPBqVOd-F9AHESLm-g',
    appId: '1:922907195481:ios:daa68148e0f22249e15948',
    messagingSenderId: '922907195481',
    projectId: 'scandit-f9d6a',
    storageBucket: 'scandit-f9d6a.appspot.com',
    androidClientId: '922907195481-pngo5qc1migj615k67soijhol81u8cl7.apps.googleusercontent.com',
    iosClientId: '922907195481-bcfqa86ksnvr3cgpi8p1gs9h8gdspjih.apps.googleusercontent.com',
    iosBundleId: 'com.example.abhinav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoLmYkApILW7Ii5mPBqVOd-F9AHESLm-g',
    appId: '1:922907195481:ios:daa68148e0f22249e15948',
    messagingSenderId: '922907195481',
    projectId: 'scandit-f9d6a',
    storageBucket: 'scandit-f9d6a.appspot.com',
    androidClientId: '922907195481-pngo5qc1migj615k67soijhol81u8cl7.apps.googleusercontent.com',
    iosClientId: '922907195481-bcfqa86ksnvr3cgpi8p1gs9h8gdspjih.apps.googleusercontent.com',
    iosBundleId: 'com.example.abhinav',
  );
}
